      SUBROUTINE ushift(LINE)
C
C..   THIS ROUTINE UPSHIFTS AN INPUT LINE
C
      INTEGER*2 ICHAR1,ICHAR2,LINE(40)
      DO 3 I=1,40
      ICHAR1 = LINE(I) / 256
C..   IF THE TOP BYTE IS BETWEEN 'a' AND 'z', UPSHIFTS IT ...
      IF(.NOT.(ICHAR1 .GE. 97 .AND. ICHAR1 .LE.122)) GOTO 1
      ICHAR1 = ICHAR1 - 32
    1 ICHAR2 = LINE(I) - 256 * (LINE(I) / 256)
C..   IF THE BOTTOM BYTE IS BETWEEN 'a' AND 'z', UPSHIFTS IT ...
      IF(.NOT.(ICHAR2 .GE. 97 .AND. ICHAR2 .LE.122)) GOTO 2
      ICHAR2 = ICHAR2 - 32
    2 LINE(I) = (256 * ICHAR1) + ICHAR2
    3 CONTINUE
      RETURN
      END
